import { IStoreURLs } from "./types";

const storeUrls: IStoreURLs = {
  Steam: "https://store.steampowered.com/",
  GamersGate: "https://www.gamersgate.com/",
  GreenManGaming: "https://www.greenmangaming.com/",
  Amazon: "https://www.amazon.com/",
  GameStop: "https://www.gamestop.com/",
  Direct2Drive: "https://www.direct2drive.com/",
  GOG: "https://www.gog.com/",
  Origin: "https://www.origin.com/",
  "Get Games": "https://www.getgames.com/",
  "Shiny Loot": "https://www.shinyloot.com/",
  "Humble Store": "https://www.humblebundle.com/store",
  Desura: null,
  Uplay: "https://store.ubi.com/",
  IndieGameStand: null,
  Fanatical: "https://www.fanatical.com/",
  Gamesrocket: "https://www.gamesrocket.com/",
  "Games Republic": null,
  SilaGames: null,
  Playfield: null,
  ImperialGames: null,
  WinGameStore: "https://www.wingamestore.com/",
  FunStockDigital: null,
  GameBillet: "https://www.gamebillet.com/",
  Voidu: "https://www.voidu.com/",
  "Epic Games Store": "https://www.epicgames.com/store/en-US/",
  "Razer Game Store": null,
  Gamesplanet: "https://us.gamesplanet.com/",
  Gamesload: "https://www.gamesload.com/",
  "2Game": "https://2game.com/",
  IndieGala: "https://www.indiegala.com/",
  "Blizzard Shop": "https://shop.battle.net/",
  AllYouPlay: null,
  DLGamer: "https://www.dlgamer.com/",
  Noctre: "https://noctre.com/",
  DreamGame: "https://dreamgame.com/",
};

export default storeUrls;
